Replace ILI9341::clear(int) w/ILI9341::clear()
The current code is complied with error of:
HZK16:42: error: no matching function for call to 'ILI9341::clear(int)'
   M5.Lcd.clear(BLACK);

It is because the old ILI9341::clear(int) function is no longer valid. Need to be replaced with ILI9341::clear().